# Generated by Django 4.0 on 2021-12-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_tag_article_tags_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable')], default=0),
        ),
    ]
