# Generated by Django 4.0 on 2021-12-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.TextField(null=True),
        ),
    ]
