# Generated by Django 4.0 on 2021-12-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='authors'),
        ),
    ]
